routes/web.php
<?php

use App\Http\Controllers\Web\ReportController;
use App\Http\Controllers\Web\ProductController;
use App\Http\Controllers\Web\CategoryController;
use App\Http\Controllers\Web\HomeController;
use App\Http\Controllers\Web\SizeController;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    App::setLocale('kh');
    return view('welcome');
});

Auth::routes();

Route::middleware('auth')->group(function () {
    Route::get('/home', [HomeController::class, 'index'])->name('home');
    Route::resource('product', ProductController::class);
    Route::resource('category', CategoryController::class);
    Route::resource('size', SizeController::class);
    Route::get('/report/product', [ReportController::class, 'product'])->name('report_product');  
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use HasFactory, SoftDeletes;
    protected $fillable = ['code', 'name', 'price', 'image_path', 'size_id', 'category_id', 'description'];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function size()
    {
        return $this->belongsTo(Size::class);
    }
}

app/Http/Controllers/API/ProductController.php
<?php
   
namespace App\Http\Controllers\API;

use App\Http\Controllers\API\BaseController;
use App\Models\Product;
use App\Http\Resources\ProductResource;
   
class ProductController extends BaseController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all();
    
        return $this->sendResponse(ProductResource::collection($products), 'Products retrieved successfully.');
    }
 
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = Product::find($id);
  
        if (is_null($product)) {
            return $this->sendError('Product not found.');
        }
   
        return $this->sendResponse(new ProductResource($product), 'Product retrieved successfully.');
    }
}

app/Http/Controllers/Web/ProductController.php
<?php

namespace App\Http\Controllers\Web;

use App\Http\Controllers\Controller;
use App\Http\Requests\ProductRequest;
use App\Models\Product;
use App\Models\Category;
use App\Models\Size;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $products = Product::all();
        // foreach($products as $product){
        //     return dd($product->category->name);
        // }
        return view('product.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $categories = Category::all();
        $sizes = Size::all();

        return view('product.create', compact('categories', 'sizes'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductRequest $request)
    {
        $input = $request->all();
        if ($request->file('image_path')) {
            $fileName =  "image-".$request->image_path->getClientOriginalName(); 
            $request->image_path->move(public_path('images'), $fileName);
            $input['image_path'] = $fileName;
        }
        Product::create($input);
        return redirect()->route('product.index')->with('success','Product created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        //
        $categories = Category::with('products')->get();
        $sizes = Size::with('products')->get();

        return view('product.edit', compact('product', 'categories', 'sizes'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(ProductRequest $request, Product $product)
    {
        $input = $request->all();
        $input['image_path'] = $product->image_path;
        if ($request->file('image_path')) {
            $fileName =  "image-".$request->image_path->getClientOriginalName(); 
            $request->image_path->move(public_path('images'), $fileName);
            $input['image_path'] = $fileName;
        }
        $product->update($input);
        return redirect()->route('product.index')->with('success','Product updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        //
        $product->delete();
        return redirect()->route('product.index')->with('success','Product deleted successfully');
    }
}

resources/views/product/create.blade.php
@extends('product.layout')
@section('content')
<section class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">{{__('Create New Product')}}</h3>
                    </div>
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <strong>{{__('Warning!')}}</strong>{{__(' Please check your input code')}}<br><br>
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <form role="form" enctype="multipart/form-data" action="{{route('product.store')}}" method="post">
                        {{csrf_field()}}
                        <div class="card-body box-profile">
			                <div class="text-center">
                                <img id="image_preview_container" class="profile-user-img img-fluid img-thumbnail" style="width:100px; height: 100px;" src="/dashboard/dist/img/boxed-bg.png" alt="User profile picture">
                                <input type="file" name="image_path" id="imgprofile" class="form-control d-none">
                            </div>
							<div class="text-center" id="edit">
								<label for="name">{{__('Choose')}}</label>
							</div>
                            <div class="form-group">
                                <label for="code">{{__('Code')}}</label>
                                <input type="text" class="form-control" name="code" value="" placeholder={{__("Code")}}>
                                {{-- <div class="input-group">
                                    <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-code"></i></span>
                                    </div>
                                    <input type="text" class="form-control" name="code" value="" placeholder={{__("Code")}}>
                                </div> --}}
                            </div>
                            <div class="form-group">
                                <label for="name">{{__('Name')}}</label>
                                <input type="text" class="form-control" name="name" value="" placeholder={{__("Name")}}>
                                {{-- <div class="input-group">
                                    <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-code"></i></span>
                                    </div>
                                    <input type="text" class="form-control" name="name" value="" placeholder={{__("Name")}}>
                                </div> --}}
                            </div>
                            <div class="form-group">
                                <label for="category">{{__('Category')}}</label>
                                <select name="category_id" class="form-control select2bs4" style="width: 100%;">
                                    @foreach($categories as $data)
                                    <option value="{{$data->id}}">{{$data->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="category">{{__('Size')}}</label>
                                <select name="size_id" class="form-control select2bs4" style="width: 100%;">
                                    @foreach($sizes as $data)
                                    <option value="{{$data->id}}">{{$data->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="price">{{__('Price')}}</label>
                                <div class="input-group">
                                    {{-- <div class="input-group-prepend">
                                        <span class="input-group-text">$</span>
                                    </div> --}}
                                    <input type="text" class="form-control" name="price" value="" placeholder={{__("Price")}}>
                                    <div class="input-group-append">
                                        <span class="input-group-text">$</span>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="description">{{__('Description')}}</label>
                                <input type="text" class="form-control editdescription" name="description" value="" placeholder={{__("Description")}}>
                            </div>
                        </div>
                        <div class="card-footer">
                            <a class="btn btn-default float-left" href="{{ route('product.index') }}">{{__('Cancel')}}</a>
                            <button type="submit" class="btn btn-primary float-right">{{__('Add')}}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

@push('scripts')
<script>
	$(document).ready(() => {
        $('#edit').click(() => {
            $('#imgprofile').click();
        });
        $('#imgprofile').change(function(){
            let reader = new FileReader();
       
            reader.onload = (e) => { 
        
                $('#image_preview_container').attr('src', e.target.result); 
            }
       
            reader.readAsDataURL(this.files[0]); 
         
        });
    })
</script>
@endpush

resources/views/product/edit.blade.php
@extends('product.layout')
@section('content')
<section class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-12">
                <div class="card card-info">
                    <div class="card-header">
                        <h3 class="card-title">{{__('Edit Product')}}</h3>
                    </div>
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <strong>{{__('Warning!')}}</strong>{{__(' Please check your input code')}}<br><br>
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <form role="form" enctype="multipart/form-data" action="{{route('product.update', $product->id)}}" method="post">
                        {{method_field('PUT')}}
                        {{csrf_field()}}
                        <div class="card-body">
                            <div class="text-center">
                                <img id="image_preview_container" class="profile-user-img img-fluid img-thumbnail" style="width:100px; height: 100px;" src="/images/{{$product->image_path}}" alt="User profile picture">
                                <input type="file" name="image_path" value="{{$product->image_path}}" id="imgprofile" class="form-control d-none">
                            </div>
							<div class="text-center" id="edit">
								<label for="name">{{__('Choose')}}</label>
							</div>
                            <div class="form-group">
                                <label for="code">{{__('Code')}}</label>
                                <input type="text" class="form-control" name="code" value="{{$product->code}}" placeholder={{__("Code")}}>
                            </div>
                            <div class="form-group">
                                <label for="name">{{__('Name')}}</label>
                                <input type="text" class="form-control" name="name" value="{{$product->name}}" placeholder={{__("Name")}}>
                            </div>
                            <div class="form-group">
                                <label for="category">{{__('Category')}}</label>
                                <select class="form-control select2bs4" name="category_id" style="width: 100%;">
                                    @foreach($categories as $category)
                                        @if($category->id==$product->category_id)
                                            <option value="{{ $category->id }}" selected="true">{{ $category->name }}</option>
                                        @else
                                            <option value="{{ $category->id }}">{{ $category->name }}</option>
                                        @endif
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="size">{{__('Size')}}</label>
                                <select class="form-control select2bs4" name="size_id" style="width: 100%;">
                                    @foreach($sizes as $size)
                                        @if($size->id==$product->size_id)
                                            <option value="{{ $size->id }}" selected="true">{{ $size->name }}</option>
                                        @else
                                            <option value="{{ $size->id }}">{{ $size->name }}</option>
                                        @endif
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="price">{{__('Price')}}</label>
                                <div class="input-group">
                                    <input type="text" class="form-control" name="price" value="{{$product->price}}" placeholder={{__("Price")}}>
                                    <div class="input-group-append">
                                        <span class="input-group-text">$</span>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="description">{{__('Description')}}</label>
                                <input type="text" class="form-control editdescription" name="description" value="{{$product->description}}" placeholder={{__("Description")}}>
                            </div>
                        </div>
                        <div class="card-footer">
                            <a class="btn btn-default float-left" href="{{ route('product.index') }}">{{__('Cancel')}}</a>
                            <button type="submit" class="btn btn-info float-right">{{__('Edit')}}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

@push('scripts')
<script>
	$(document).ready(() => {
        $('#edit').click(() => {
            $('#imgprofile').click();
        });
        $('#imgprofile').change(function(){
            let reader = new FileReader();
       
            reader.onload = (e) => { 
        
                $('#image_preview_container').attr('src', e.target.result); 
            }
       
            reader.readAsDataURL(this.files[0]); 
         
        });
    })
</script>
@endpush

resources/views/product/index.blade.php
@extends('product.layout')
@section('content')
<!-- Main content -->
<section class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-12">
				@if ($message = Session::get('success'))
					<div class="alert alert-success">
						<p>{{ $message }}</p>
					</div>
				@endif
				<div class="card">
					<div class="card-header">
                        <a class="btn btn-primary float-left" href="{{ route('product.create') }}"><i class="fas fa-plus-square"> {{__('New')}}</i></a>
					</div>
					<!-- /.card-header -->
					<div class="card-body">
						<table id="example1" class="table table-bordered table-striped">
							<thead>
								<tr role="row">
									<th>{{__('Code')}}</th>
									<th>{{__('Name')}}</th>
									<th>{{__('Category')}}</th>
									<th>{{__('Size')}}</th>
									<th>{{__('Price')}}</th>
									<th>{{__('Description')}}</th>
									<th>{{__('Action')}}</th>
								</tr>
							</thead>
							<tbody>
							@foreach($products as $product)
								<tr>
									<td>{{$product->code}}</td>
									<td>{{$product->name}}</td>
									<td>{{$product->category->name}}</td>
									@if ($product->size)
										<td>{{$product->size->name}}</td>
									@else
										<td></td>
									@endif
									<td>{{$product->price}}</td>
									<td>{{$product->description}}</td>
									<td>
										<form action="{{ route('product.destroy',$product->id) }}" method="POST">
											{{-- <a class="btn btn-success" href="{{ route('product.show', $product->id) }}"><i class="fas fa-eye"></i></a> --}}
											<a class="btn btn-info" href="{{ route('product.edit', $product->id) }}"><i class="fas fa-edit"></i></a>
											@csrf
											@method('DELETE')
											<button class="btn btn-danger" onclick="return confirm('Are you sure?')"><i class="fas fa-trash-alt"></i></button>
										</form>
									</td>
								</tr>
							@endforeach
							</tbody>
							<tfoot>
								<tr>
									<th>{{__('Code')}}</th>
									<th>{{__('Name')}}</th>
									<th>{{__('Category')}}</th>
									<th>{{__('Size')}}</th>
									<th>{{__('Price')}}</th>
									<th>{{__('Description')}}</th>
									<th>{{__('Action')}}</th>
								</tr>
							</tfoot>
						</table>
					</div>
					<!-- /.card-body -->
				</div>
				<!-- /.card -->
			</div>
			<!-- /.col -->
		</div>
		<!-- /.row -->
	</div>
	<!-- /.container-fluid -->
</section>
<!-- /.content -->
@endsection

resources/views/product/layout.blade.php
@extends('master')

@section('content-header')
	<!-- Content Header (Page header) -->
    <section class="content-header">
		<div class="container-fluid">
		  <div class="row mb-2">
			<div class="col-sm-6">
			  <h1>{{__('Product')}}</h1>
			</div>
			<div class="col-sm-6">
			  <ol class="breadcrumb float-sm-right">
				<li class="breadcrumb-item"><a href="{{route('home')}}">{{__('Home')}}</a></li>
				<li class="breadcrumb-item active">{{__('Product')}}</li>
			  </ol>
			</div>
		  </div>
		</div><!-- /.container-fluid -->
	  </section>
@endsection

@section('content')
	@yield('content')
@endsection

@push('scripts')
	<script>
		$(function () {
		  $("#example1").DataTable({
			"responsive": true,
			"autoWidth": false,
			"language": {
				"emptyTable": "No Product available in database"//Change your default empty table message
			}
		  });
		});
	  </script>
@endpush