routes/web.php
<?php

use App\Http\Controllers\Web\ReportController;
use App\Http\Controllers\Web\ProductController;
use App\Http\Controllers\Web\CategoryController;
use App\Http\Controllers\Web\HomeController;
use App\Http\Controllers\Web\SizeController;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    App::setLocale('kh');
    return view('welcome');
});

Auth::routes();

Route::middleware('auth')->group(function () {
    Route::get('/home', [HomeController::class, 'index'])->name('home');
    Route::resource('product', ProductController::class);
    Route::resource('category', CategoryController::class);
    Route::resource('size', SizeController::class);
    Route::get('/report/product', [ReportController::class, 'product'])->name('report_product');  
});

resources/views/layouts/master/footer.blade.php
<footer class="main-footer text-sm">
    <strong>Copyright &copy; 2020 <a href="#">Tribie.info</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 0.0.1
    </div>
</footer>

resources/views/layouts/master/navbar.blade.php
<nav class="main-header navbar navbar-expand navbar-dark navbar-purple border-bottom-0">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <li class="nav-item dropdown d-none d-lg-flex">
        <a class="nav-link dropdown-toggle" id="languageDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
          <img src="/icons/uk.svg" style="width: 25px; height: 20px" alt="English">
          English
        </a>
        <div class="dropdown-menu navbar-dropdown" aria-labelledby="languageDropdown">
          <a class="dropdown-item font-weight-medium" href="#">
            <img src="/icons/kh.svg" style="width: 25px; height: 20px" alt="Khmer">
            Khmer
          </a>
          {{-- <div class="dropdown-divider"></div>
          <a class="dropdown-item font-weight-medium" href="#">
            <i class="flag-icon flag-icon-es"></i>
            Espanol
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item font-weight-medium" href="#">
            <i class="flag-icon flag-icon-lt"></i>
            Latin
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item font-weight-medium" href="#">
            <i class="flag-icon flag-icon-ae"></i>
            Arabic
          </a> --}}
        </div>
      </li>
      <li class="nav-item dropdown d-none d-lg-flex">
        <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
          <i class="fas fa-sign-out-alt" style="font-size:26px; color: rgba(255,255,255,.80);"></i>
        </a>
        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
            @csrf
        </form>
      </li>
    </ul>
  </nav>

resources/views/layouts/master/sidebar.blade.php
<aside class="main-sidebar elevation-4 sidebar-dark-purple">
    <!-- Brand Logo -->
    <a href="/home" class="brand-link navbar-purple">
      <img src="{{url('/dashboard/dist/img/AdminLTELogo.png')}}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text font-weight-light">{{__('Stock Management')}}</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{{url('/dashboard/dist/img/user2-160x160.jpg')}}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">{{ Auth::user()->name }}</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column nav-child-indent nav-legacy nav-flat" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item">
            <a href="{{ route('home') }}" class="nav-link {{ Request::segment(1) === 'home' ? 'active' : null }}">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                {{__('Dashboard')}}
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ route('product.index') }}" class="nav-link {{ Request::segment(1) === 'product' ? 'active' : null }}">
              <i class="nav-icon fab fa-product-hunt"></i>
              <p>
                {{__('Product')}}
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ route('category.index') }}" class="nav-link {{ Request::segment(1) === 'category' ? 'active' : null }}">
              <i class="nav-icon fas fa-list-alt"></i>
              <p>
                {{__('Category')}}
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ route('size.index') }}" class="nav-link {{ Request::segment(1) === 'size' ? 'active' : null }}">
              <i class="nav-icon fas fa-list-alt"></i>
              <p>
                {{__('Size')}}
              </p>
            </a>
          </li>
          <li class="nav-item has-treeview">
            <a href="#" class="nav-link {{ Request::segment(1) === 'report' ? 'active' : null}}">
              <i class="nav-icon fas fa-file"></i>
              <p>
                {{__('Report')}}
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{{ route('report_product') }}" class="nav-link {{ Request::segment(2) === 'product' ? 'active' : null }}">
                  <i class="nav-icon fas fa-receipt"></i>
                  <p>
                    {{__('Product')}}
                  </p>
                </a>
              </li>
            </ul>
          </li>
          <li class="nav-item has-treeview">
            <a href="#" class="nav-link {{ Request::segment(1) === 'language' ? 'active' : null}} {{Request::segment(1) === 'branch' ? 'active' : null}}">
              <i class="nav-icon fas fa-toolbox"></i>
              <p>
                {{__('System')}}
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="/branch" class="nav-link {{ Request::segment(1) === 'branch' ? 'active' : null }}">
                  <i class="nav-icon fas fa-code-branch"></i>
                  <p>
                    {{__('Branch')}}
                  </p>
                </a>
              </li>
              <li class="nav-item">
                <a href="/language" class="nav-link {{ Request::segment(1) === 'language' ? 'active' : null }}">
                  <i class="fas fa-language nav-icon"></i>
                  <p>{{__('Language')}}</p>
                </a>
              </li>
            </ul>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>