routes/web.php
<?php

use App\Http\Controllers\Web\ReportController;
use App\Http\Controllers\Web\ProductController;
use App\Http\Controllers\Web\CategoryController;
use App\Http\Controllers\Web\HomeController;
use App\Http\Controllers\Web\SizeController;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    App::setLocale('kh');
    return view('welcome');
});

Auth::routes();

Route::middleware('auth')->group(function () {
    Route::get('/home', [HomeController::class, 'index'])->name('home');
    Route::resource('product', ProductController::class);
    Route::resource('category', CategoryController::class);
    Route::resource('size', SizeController::class);
    Route::get('/report/product', [ReportController::class, 'product'])->name('report_product');  
});

app/Models/Size.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Size extends Model
{
    use HasFactory, SoftDeletes;
    protected $fillable = ['name', 'description'];

    public function products()
    {
        return $this->hasMany(Product::class);
    }
}

app/Http/Controllers/Web/SizeController.php
<?php

namespace App\Http\Controllers\Web;

use App\Http\Controllers\Controller;
use App\Http\Requests\SizeRequest;
use App\Models\Size;
use Illuminate\Http\Request;

class SizeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
        $sizes = Size::all();
        
        return view('size.index', compact('sizes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
        $sizes = Size::all();
        
        return view('size.create', compact('sizes'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SizeRequest $request)
    {
        //
        Size::create($request->all());
        return redirect()->route('size.index')->with('success','Size created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Size  $size
     * @return \Illuminate\Http\Response
     */
    public function show(Size $size)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Size  $size
     * @return \Illuminate\Http\Response
     */
    public function edit(Size $size)
    {
        //
        $sizes = Size::all();

        return view('size.edit', compact('size', 'sizes'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Size  $size
     * @return \Illuminate\Http\Response
     */
    public function update(SizeRequest $request, Size $size)
    {
        //
        $size->update($request->all());
        return redirect()->route('size.index')->with('success','Size updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Size  $size
     * @return \Illuminate\Http\Response
     */
    public function destroy(Size $size)
    {
        //
        $size->delete();
        return redirect()->route('size.index')->with('success','Size deleted successfully');
    }
}

resources/views/size/create.blade.php
@extends('size.layout')
@section('content')
<section class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">{{__('Create New Category')}}</h3>
                    </div>
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <strong>{{__('Warning!')}}</strong>{{__(' Please check your input code')}}<br><br>
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <form role="form" enctype="multipart/form-data" action="{{route('size.store')}}" method="post">
                        {{csrf_field()}}
                        <div class="card-body">
                            <div class="form-group">
                                <label for="name">{{__('Name')}}</label>
                                <input type="text" class="form-control name" name="name" value="" placeholder={{__('Name')}}>
                            </div>
                            <div class="form-group">
                                <label for="description">{{__('Description')}}</label>
                                <input type="text" class="form-control editdescription" name="description" value="" placeholder={{__('Description')}}>
                            </div>
                            {{-- <div class="form-group">
                                <div class="form-group">
                                    <label for="parent">{{__('Parent')}}</label>
                                    <div class="select2-primary">
                                        <select class="select2 selectParentCategory" name="parentId[]" multiple="multiple" data-placeholder="{{__("Select Parents")}}" style="width: 100%;">
                                            @foreach($sizes as $data)
                                                <option value="{{$data->id}}">{{$data->name}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                            </div> --}}
                        </div>
                        <div class="card-footer">
                            <a class="btn btn-default float-left" href="{{ route('size.index') }}">{{__('Cancel')}}</a>
                            <button type="submit" class="btn btn-primary float-right">{{__('Add')}}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/size/edit.blade.php
@extends('size.layout')
@section('content')
<section class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-12">
                <div class="card card-info">
                    <div class="card-header">
                        <h3 class="card-title">{{__('Edit Category')}}</h3>
                    </div>
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <strong>{{__('Warning!')}}</strong>{{__(' Please check your input code')}}<br><br>
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <form role="form" enctype="multipart/form-data" action="{{route('size.update', $size->id)}}" method="post">
                        {{method_field('put')}}
                        {{csrf_field()}}
                        <div class="card-body">
                            <div class="form-group">
                                <label for="name">{{__('Name')}}</label>
                            <input type="text" class="form-control name" name="name" value="{{$size->name}}" placeholder={{__('Name')}}>
                            </div>
                            <div class="form-group">
                                <label for="description">{{__('Description')}}</label>
                                <input type="text" class="form-control editdescription" name="description" value="{{$size->description}}" placeholder={{__('Description')}}>
                            </div>
                            {{-- <div class="form-group">
                                <div class="form-group">
                                    <label for="parent">{{__('Parent')}}</label>
                                    <div class="select2-info">
                                        <select class="select2 selectParentCategory" name="parentId[]" multiple="multiple" data-placeholder="{{__('Select Parents')}}" style="width: 100%;">
                                            @foreach($sizes as $data)
                                                @if(in_array($data->id, $selectedParent))
                                                <option value="{{ $data->id }}" selected="true">{{ $data->name }}</option>
                                                @else
                                                <option value="{{ $data->id }}">{{ $data->name }}</option>
                                                @endif 
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                            </div> --}}
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-default float-left" onclick="{{ route('size.index') }}">{{__('Cancel')}}</button>
                            <button type="submit" class="btn btn-info float-right">{{__('Edit')}}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/size/index.blade.php
@extends('size.layout')
@section('content')
<!-- Main content -->
<section class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-12">
				@if ($message = Session::get('success'))
					<div class="alert alert-success">
						<p>{{ $message }}</p>
					</div>
				@endif
				<div class="card">
					<div class="card-header">
                        <a class="btn btn-primary float-left" href="{{ route('size.create') }}"><i class="fas fa-plus-square"> {{__('New')}}</i></a>
					</div>
					<!-- /.card-header -->
					<div class="card-body">
						<table id="example1" class="table table-bordered table-striped">
							<thead>
								<tr role="row">
									<th>{{__('Name')}}</th>
									<th>{{__('Description')}}</th>
									<th>{{__('Action')}}</th>
								</tr>
							</thead>
							<tbody>
							@foreach($sizes as $s)
								<tr>
									<td>{{$s->name}}</td>
									<td>{{$s->description}}</td>
									<td>
										<form action="{{ route('size.destroy',$s->id) }}" method="POST">
											<a class="btn btn-info" href="{{ route('size.edit', $s->id) }}"><i class="fas fa-edit"></i></a>
											@csrf
											@method('DELETE')
											<button class="btn btn-danger" onclick="return confirm('Are you sure?')"><i class="fas fa-trash-alt"></i></button>
										</form>
									</td>
								</tr>
							@endforeach
							</tbody>
							<tfoot>
								<tr>
									<th>{{__('Name')}}</th>
									<th>{{__('Description')}}</th>
									<th>{{__('Action')}}</th>
								</tr>
							</tfoot>
						</table>
					</div>
					<!-- /.card-body -->
				</div>
				<!-- /.card -->
			</div>
			<!-- /.col -->
		</div>
		<!-- /.row -->
	</div>
	<!-- /.container-fluid -->
</section>
<!-- /.content -->
@endsection

resources/views/size/layout.blade.php
@extends('master')

@section('content-header')
	<!-- Content Header (Page header) -->
    <section class="content-header">
		<div class="container-fluid">
		  <div class="row mb-2">
			<div class="col-sm-6">
			  <h1>{{__('Size')}}</h1>
			</div>
			<div class="col-sm-6">
			  <ol class="breadcrumb float-sm-right">
				<li class="breadcrumb-item"><a href="{{route('home')}}">{{__('Home')}}</a></li>
				<li class="breadcrumb-item active">{{__('Size')}}</li>
			  </ol>
			</div>
		  </div>
		</div><!-- /.container-fluid -->
	  </section>
@endsection

@section('content')
	@yield('content')
@endsection

@push('scripts')
	<script>
		$(function () {
		  $("#example1").DataTable({
			"responsive": true,
			"autoWidth": false,
			"language": {
				"emptyTable": "No Size available in database"//Change your default empty table message
			}
		  });
		});
	  </script>
@endpush